### ISSUE TITLE
Seriesmeta documentation

### ISSUE THREAD

**Issue by onodera-punpun** [geek1011/kepubify#16]
I'm not exactly sure what this does, where and how it pulls the metadata, some info would be nice :)

**Comment by geek1011** [comment]
`seriesmeta` adds the series metadata (shown under the title in My Books) from the books (both epub and kepub) to the kobo database. 

`seriesmeta` exists because kobo does not usually extract the series metadata from the books when importing them, unless the book is from the kobo store. 

The metadata is from the `calibre:series` and `calibre:series_index` meta tags in the epub's opf document.

**Comment by onodera-punpun** [comment]
>Note that a kepub formatted book needs the extension to be .kepub.epub, that is two extensions. Otherwise it will not recognize the book as different from a normal epub. 

https://wiki.mobileread.com/wiki/Kepub
